-- ==========================================================
-- HACKARE: PROBLEM STATEMENTS & COMPETITION SCHEMA MIGRATION
-- ==========================================================

-- 1. Create Problem Statements Table
CREATE TABLE IF NOT EXISTS public.problem_statements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  statement_code TEXT NOT NULL UNIQUE, -- e.g. PS-01 to PS-22
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  domain TEXT NOT NULL,
  max_teams INTEGER NOT NULL DEFAULT 2,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Team Problem Selections Table (1 problem per team, max 2 teams per problem)
CREATE TABLE IF NOT EXISTS public.problem_selections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  problem_id UUID REFERENCES public.problem_statements(id) ON DELETE CASCADE NOT NULL,
  team_id UUID REFERENCES public.teams(id) ON DELETE CASCADE NOT NULL UNIQUE,
  selected_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Add column to teams table if not exists for quick referencing
ALTER TABLE public.teams ADD COLUMN IF NOT EXISTS selected_problem_id UUID REFERENCES public.problem_statements(id) ON DELETE SET NULL;

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.problem_statements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.problem_selections ENABLE ROW LEVEL SECURITY;

-- Allow read access to all authenticated and anon users
DROP POLICY IF EXISTS "Allow select problem_statements" ON public.problem_statements;
CREATE POLICY "Allow select problem_statements" ON public.problem_statements FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow select problem_selections" ON public.problem_selections;
CREATE POLICY "Allow select problem_selections" ON public.problem_selections FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow all for authenticated problem_selections" ON public.problem_selections;
CREATE POLICY "Allow all for authenticated problem_selections" ON public.problem_selections FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all for service role on problem_statements" ON public.problem_statements;
CREATE POLICY "Allow all for service role on problem_statements" ON public.problem_statements FOR ALL USING (true) WITH CHECK (true);

-- 5. Additional column in submissions for system architecture & demo fields if not present
ALTER TABLE public.submissions ADD COLUMN IF NOT EXISTS github_url TEXT;
ALTER TABLE public.submissions ADD COLUMN IF NOT EXISTS chatgpt_link_2 TEXT;

-- 6. Academic details columns in users table
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS reg_no TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS dept TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS section TEXT;
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS year TEXT;

-- 7. Problem statements release status column
ALTER TABLE public.leaderboard_config ADD COLUMN IF NOT EXISTS is_problems_released BOOLEAN DEFAULT false;

-- 8. Custom Team ID code in teams table
ALTER TABLE public.teams ADD COLUMN IF NOT EXISTS team_code TEXT;

-- -- 9. Insert / Seed 21 Official Reverse Engineering Problem Statements
INSERT INTO public.problem_statements (statement_code, domain, title, description, max_teams)
VALUES
  ('PS-01', 'Feed Systems & Multi-Tier Caching', 'Where Did the Old Reels Go? – Instagram Feed & Cache', 'When an influencer''s profile is opened, only the most recent reels load instantly even though thousands exist in total. As the user scrolls further back, older reels must still appear smoothly without the app fetching or rendering everything at once. Your task is to reverse-engineer how Instagram likely handles this at scale — including how content is paginated, what gets cached at the client vs. server, and how storage tiers (hot vs. cold) are organized. Design a simplified system that demonstrates efficient retrieval of historical content using pagination, lazy loading, and layered caching. Clearly justify your choice of cache eviction policy and data-fetching strategy. The final design should show how it avoids unnecessary load while keeping scroll experience seamless', 2),
  ('PS-02', 'Geospatial Indexing & Real-Time Dispatch', 'Who Gets the Ride? – Rapido/Ola/Uber Rider Allocation', 'In a busy city, thousands of ride requests can hit the platform within the same second, each needing to be matched with an available driver almost instantly. Your task is to design a rider-driver matching engine that decides allocation based on live location, driver availability, distance, estimated time of arrival, and request priority (e.g., surge zones or waiting time). Address how the system avoids double-assigning a driver and how it handles a driver rejecting or timing out on a request. Explore the underlying data structures (e.g., geospatial indexing) needed to search nearby drivers efficiently. The design should balance fairness, speed, and resource utilization under high concurrent load.', 2),
  ('PS-03', 'Video Streaming & CDN Distribution', 'One Movie, Millions of Screens – Netflix Streaming', 'When a popular title is released, millions of users may stream it at the exact same time from different regions and devices. Your task is to reverse-engineer how such simultaneous demand is served without a single server buckling under load. Explore how video is broken into segments, how metadata and thumbnails are delivered separately from the main stream, and how content delivery networks (CDNs) cache data closer to users. Design a simplified architecture showing request flow from a user''s play button click to the video segment being served. Explain how caching and geographic distribution reduce latency and central server load.', 2),
  ('PS-04', 'Live Broadcasting & Traffic Surge Resilience', 'Hotstar Peak-Time Challenge – Millions Watching Together', 'During a marquee live event like a cricket final, millions of viewers attempt to start streaming within the same few minutes, creating an extreme, short-duration traffic spike. Your task is to design a system that can absorb this sudden surge without crashing or significantly degrading video quality. Cover load balancing across servers, session management for millions of concurrent viewers, and caching strategies specific to live (not on-demand) content. Discuss how the system scales up rapidly before the event and scales down afterward. The design should highlight trade-offs between cost, latency, and reliability during peak load.', 2),
  ('PS-05', 'Recommendation Engines & Infinite Feeds', 'YouTube Infinite Feed – How Does It Keep Loading?', 'As a user scrolls the YouTube homepage or Shorts feed, new videos keep appearing seamlessly, as if the list never ends. Your task is to recreate a simplified version of this infinite-scroll mechanism. Explain how pagination or cursor-based fetching works behind the scenes, how the next batch of videos is prefetched before the user reaches the end, and how a recommendation engine decides what to fetch next. Address how caching avoids repeated computation of recommendations for the same session. The final design should demonstrate smooth, low-latency continuous loading without ever fetching the "entire" dataset at once.', 2),
  ('PS-06', 'High-Concurrency Ticketing & Lock Serialization', 'Tatkal Rush – One Train, Thousands of Users', 'At exactly 10 AM, thousands of users simultaneously attempt to book a handful of remaining Tatkal train seats, all racing for the same limited inventory. Your task is to design a booking system that guarantees no seat is sold twice (no double booking) despite this extreme concurrency. Explore concepts like database locking, optimistic vs. pessimistic concurrency control, and request queuing to serialize competing requests fairly. Discuss how the system handles a user who reserves a seat but doesn''t complete payment in time. The design must clearly demonstrate consistency and fairness under a massive concurrent write load.', 2),
  ('PS-07', 'Distributed Locking & State Consistency', 'Bus Seat Vanishing Act – Real-Time Seat Booking', 'When only a few bus seats remain, hundreds of users may try to select and book the same seats within seconds of each other. Your task is to design a real-time seat availability system that temporarily locks a seat once a user selects it, preventing others from booking it simultaneously. Address what happens if the user abandons the booking — the lock must expire and release the seat automatically. Cover how the system maintains transactional consistency between seat locking, payment, and final confirmation. The design should prevent both double-booking and seats getting "stuck" as falsely unavailable.', 2),
  ('PS-08', 'High-Load Systems & Read Caching', 'The Result Day Rush – College Portal Under Pressure', 'On result day, thousands of students hit the college portal within the same few minutes, causing it to slow down, throw timeouts, or crash entirely. Your task is to first identify the likely bottlenecks — database overload, lack of caching, insufficient server capacity, or no request throttling. Then design a scalable solution using caching (for repeated result lookups), load balancing across servers, request queues to smooth traffic spikes, and database optimization (indexing, read replicas). Also address concurrency control to prevent conflicting reads/writes on student records. The final design should demonstrate graceful handling of a short, extreme traffic spike.', 2),
  ('PS-09', 'Static Content Delivery & Edge Caching', 'The Exam Paper Rush – Everyone Downloads at Once', 'When an exam paper or admit card is released, a huge number of students attempt to download the same file within a very short window. Your task is to design a file-delivery system that can handle this concentrated demand without failing. Explore the role of a CDN and caching in serving the same static file to many users without repeatedly hitting the origin server. Discuss controlled/staggered access mechanisms (e.g., queuing or scheduled release) to prevent overload. The design should ensure fast, reliable downloads for all users despite the traffic being concentrated in a narrow time window.', 2),
  ('PS-10', 'On-Demand Delivery & Fleet Optimization', 'Swiggy/Zomato Delivery Allocation', 'During a lunch or dinner rush, hundreds of food orders are placed at once, each needing to be assigned to an available delivery partner. Your task is to design an allocation algorithm that considers delivery-partner location and availability, current workload (orders already assigned), restaurant location, and estimated delivery time. Address how the system avoids overloading a single delivery partner while also minimizing overall delivery time across all orders. Discuss what happens when no partner is available nearby — does the order wait, or expand the search radius? The design should balance speed, fairness, and partner efficiency at scale.', 2),
  ('PS-11', 'Flash Sales & Atomic Inventory Control', 'Amazon Flash Sale – The Last 100 Phones', 'During a flash sale, a limited stock of a popular phone (say, 100 units) faces demand from thousands of users clicking "Buy Now" within seconds. Your task is to design a system that maintains accurate inventory count and prevents overselling despite this massive concurrent demand. Explore techniques like atomic decrement operations, request queuing, and caching of "sold out" status to reduce database load. Discuss how the system fairly handles requests that arrive at nearly the same instant. The design should guarantee that exactly the available stock — no more, no less — is sold.', 2),
  ('PS-12', 'Fintech & Idempotent Transaction Processing', 'UPI Payment Storm – Everyone Pays at Once', 'During a major sale event or festival, thousands of UPI payments are initiated simultaneously across the country, and the system must process each reliably. Your task is to model the transaction lifecycle — initiation, processing, success/failure, and status confirmation — under this heavy concurrent load. Address how the system handles duplicate payment requests (e.g., a user tapping "Pay" twice) and network-related retries without double-charging. Discuss how eventual consistency is managed when a payment''s final status isn''t known immediately. The design should ensure that every transaction ends in one, and only one, definitive state.', 2),
  ('PS-13', 'Cloud Synchronization & Conflict Resolution', 'Google Drive – Same File, Multiple Devices', 'A user edits a document on their laptop while the same file is also open or being accessed on their phone or another device. Your task is to design a synchronization system that keeps the file consistent across all devices without losing any changes. Explore how versioning tracks changes over time, how conflicts are detected when two edits happen close together, and what resolution strategy is used (e.g., last-write-wins, merge, or manual conflict resolution). Discuss the role of caching for offline access and how changes are reconciled once the device reconnects. The design should ensure no silent data loss across devices.', 2),
  ('PS-14', 'Real-Time Presence & Heartbeat Management', 'WhatsApp Last Seen – Who Is Actually Online?', 'At any given moment, millions of users are connecting, disconnecting, and reconnecting to WhatsApp''s servers, yet the app must accurately show each contact''s "online" or "last seen" status. Your task is to design a presence-management system that tracks this efficiently at scale. Explore how periodic heartbeat signals confirm a user is still connected, how session state is maintained, and how disconnections (including sudden ones, like a phone dying) are detected without excessive delay. Discuss how this data is pushed to relevant contacts in real time without polling constantly. The design should minimize server load while keeping presence information reasonably accurate.', 2),
  ('PS-15', 'Ephemeral Storage & TTL Lifecycle Expiry', 'Instagram Stories – 24-Hour Disappearing Content', 'A story posted by a user must automatically become inaccessible exactly 24 hours after posting, even though it may have received millions of views in that window. Your task is to design the underlying expiry mechanism — deciding whether deletion happens via a scheduled job, lazy check-on-access, or TTL-based storage expiry. Address how media (images/videos) is stored and cached efficiently given its temporary nature, and how view counts are tracked accurately under high concurrent viewing. Discuss trade-offs between immediate deletion (compute-heavy) and lazy expiry (storage-heavy). The design should reliably enforce the 24-hour rule at scale.', 2),
  ('PS-16', 'Audio Streaming & Progressive Buffering', 'Spotify – Why Does the Song Start So Fast?', 'When a user taps play on a song, audio begins almost instantly, even though the complete audio file may be several megabytes and hasn''t fully downloaded yet. Your task is to design a simplified streaming system that explains this near-instant playback. Explore how audio is broken into small chunks that are downloaded and buffered progressively, how playback starts once enough of the initial buffer is ready, and how caching (locally or via CDN) speeds up subsequent plays. Address how the system adapts to changing network conditions (adaptive bitrate) to avoid buffering interruptions. The design should demonstrate smooth playback start and continuity despite incomplete downloads.', 2),
  ('PS-17', 'Graph Routing & Dynamic Pathfinding', 'Google Maps – Finding the Fastest Route', 'A user requests directions from point A to B, but traffic conditions along possible routes are constantly changing as thousands of other users'' location data streams in. Your task is to build a simplified routing system that selects the fastest path using graph-based algorithms (e.g., Dijkstra''s or A*) over a road network. Explore how the system incorporates real-time traffic updates to re-weight edges (roads) dynamically, and how caching of frequently-requested routes reduces recomputation. Discuss how the route is recalculated if conditions change mid-journey. The design should balance accuracy of real-time data against computation speed.', 2),
  ('PS-18', 'Search Engines & Inverted Indexing', 'Amazon Search – Finding a Product in Milliseconds', 'A user searches for a product among hundreds of millions of listings, yet relevant results appear within milliseconds. Your task is to build a simplified search system that supports fast keyword matching across a massive catalog. Explore how an inverted index enables quick lookups instead of scanning every product, how filters (price, brand, rating) narrow results efficiently, and how relevance ranking scores and orders matching products. Discuss how the index is kept up to date as new products are added or prices change. The design should demonstrate the trade-off between index freshness and query speed.', 2),
  ('PS-19', 'Feed Ranking & Personalized Algorithms', 'LinkedIn Feed – What Should You See First?', 'Two different users viewing LinkedIn at the same time see completely different sets of posts in a different order, personalized to each of them. Your task is to design a feed-ranking system that decides what content appears and in what order. Explore how factors like post recency, engagement (likes/comments), the user''s relationship with the poster, and topical relevance are combined into a ranking score. Discuss how the system balances fresh content against highly engaging older content, and how it avoids showing the same post repeatedly. The design should produce a personalized, coherent feed ordering for each user.', 2),
  ('PS-20', 'High-Throughput Ingestion & Queue Processing', 'Online Exam Portal – 10,000 Students Submit at 11:59 PM', 'As the deadline approaches, thousands of students rush to submit their answers within the same final minute, putting extreme write pressure on the system. Your task is to design a submission system that reliably handles this concurrent write burst without losing or corrupting any student''s data. Explore how autosave reduces last-minute data loss risk, how request queues smooth the submission spike, and how duplicate submissions (e.g., a student clicking submit twice) are prevented. Discuss the consistency guarantees needed to ensure every valid submission before the deadline is recorded, even under load. The design should demonstrate zero data loss under peak concurrent writes.', 2),
  ('PS-21', 'Resumable Uploads & Fault Tolerance', 'Cloud Drive Upload – 1 GB File on a Slow Network', 'A user tries to upload a large 1 GB file over an unstable or slow network connection, and the upload keeps failing partway through, forcing a frustrating restart from zero. Your task is to design a robust upload system that tolerates such interruptions gracefully. Explore how the file is split into chunks that are uploaded and tracked independently, how checksums verify each chunk''s integrity, and how a resumable upload mechanism picks up from the last successfully uploaded chunk rather than restarting. Discuss the retry strategy for failed chunks and how upload state is persisted across sessions or app restarts. The design should guarantee the file eventually uploads completely and correctly despite an unreliable network.', 2)
ON CONFLICT (statement_code) DO UPDATE 
SET 
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  domain = EXCLUDED.domain,
  max_teams = EXCLUDED.max_teams;

-- 10. Update existing problem statements to max_teams = 2
UPDATE public.problem_statements SET max_teams = 2 WHERE max_teams != 2;
